<h1> Logaritmo Discreto


![Figure 1](./img/dlog.png)

El logaritmo discreto, es la base de la seguridad de los metodos anteriores. Consiste en encontrar las llaves privadas de Bob y Alicia, a y b. Imaginemos que existe un tercer sujeto llamado Pancho. Pancho intercepta la comunicación entre Alicia y Bob y lo único que ve en el camino son A y B, es decir $g^a$ y $g^b$. Si Pancho pudiera saber a o b, entonces solo tomo ya sea A o B y lo eleva a la llave que encontro. Para encontrarlo necesita del logaritmo discreto.

El logaritmo discreto se define como:

$\ g^a \equiv \ A \ mod\ p$

Donde A, g y p son conocidos y buscamos a, es decir:

$ a \equiv \ log_g(A) \ mod\ p$

Hay varias formas de encontrar el logaritmo discreto. Tomemos del ejemplo anterior en el encriptado de Diffie Helman, los mismos números. 

Digamos que Pancho consigue A = 656334248, sabemos que g = 13 y p = 3367900313


In [16]:
A = 656334248
g = 13
p = 3367900313


    

<h3> Algoritmo Pohlig-Helman

In [17]:
from sympy.ntheory import factorint
factorint(3367900312)

{2: 3, 7: 1, 109: 1, 551753: 1}

Tomamos primero el factor $2^3$

In [18]:
int1=int((3367900313-1)/2)

alpha1=pow(13,int1,p)
print("Alpha1 =",alpha1)
beta1=pow(A,int1,p)
print("Beta1 =",beta1)


Alpha1 = 3367900312
Beta1 = 3367900312


Por lo tanto $x_0=1$, y ahora incrementamos $2^2$

In [19]:
s=modinv(g,p)
A1=A*s%p
print(A1)
int2=int((3367900312)/4)
beta2=pow(A1,int2,p)
print("Beta2 =",beta2)
prueba=pow(alpha1,5,p)
print("prueba =",prueba)

3159318308
Beta2 = 3367900312
prueba = 3367900312


Por lo tanto $x_1=1$

In [20]:
s2=modinv(g,p)
A2=A1*s2*s2%p
print(A2)
int3=int((3367900312)/8)
beta3=pow(A2,int3,p)
print("Beta3 =",beta3)


1732536954
Beta3 = 3367900312


Por lo tanto $x_2=1$, y la primera ecuación es: $x_1 = x_0+2*x_1+4*x_2 \equiv 7\ mod \ 8$

Tomamos segundo el factor $7$

In [21]:
int11=int((3367900313-1)/7)

alpha11=pow(13,int11,p)
print("Alpha1 =",alpha11)
beta11=pow(A,int11,p)
print("Beta1 =",beta11)

Alpha1 = 2974477553
Beta1 = 1


Por lo tanto  $x_1=0$ y la segunda ecuación es: $x_2 \equiv 0\ mod \ 7$

Tomamos tercero el factor $109$

In [22]:
int111=int((3367900313-1)/109)

alpha111=pow(13,int111,p)
print("Alpha1 =",alpha111)
beta111=pow(A,int111,p)
print("Beta1 =",beta111)

Alpha1 = 2920505388
Beta1 = 2497218448


In [23]:
prueba=pow(alpha111,3,p)
print (prueba)

2497218448


Por lo tanto  $x_1=3$ y la segunda ecuación es: $x_3 \equiv 3\ mod \ 109$


Tomamos por último el factor $551753$

In [24]:
int1111=int((3367900313-1)/551753)

alpha1111=pow(13,int1111,p)
print("Alpha1 =",alpha1111)
beta1111=pow(A,int1111,p)
print("Beta1 =",beta1111)

Alpha1 = 600054388
Beta1 = 2491247764


In [25]:
i=0
result=0
while result != beta1111:
    result=pow(alpha1111,i,p)
    i=i+1
print(i-1)
print (result)

46552
2491247764


In [26]:
print(pow(alpha1111,46552,p))

2491247764


Por lo tanto  $x_1=46552$ y la segunda ecuación es: $x_4 \equiv 46552\ mod \ 551753$

In [49]:
def extended_gcd2(a, b):
    """Return (r, s, d) where a*r + b*s = d and d = gcd(a,b)"""
    x,y = 0, 1
    lastx, lasty = 1, 0

    while b:
        a, (q, b) = b, divmod(a,b)
        x, lastx = lastx-q*x, x
        y, lasty = lasty-q*y, y

    return (lastx, lasty, a)
def chinese_remainder_theorem(items):
  """Solve the chinese remainder theorem
  Given a list of items (a_i, n_i) solve for x such that x = a_i (mod n_i)
  such that 0 <= x < product(n_i)
  Assumes that n_i are pairwise co-prime.
  """

  # Determine N, the product of all n_i
  N = 1
  for a, n in items:
    N *= n

  # Find the solution (mod N)
  result = 0
  for a, n in items:
    m = N//n
    r, s, d = extended_gcd2(n, m)
    if d != 1:
      raise "Input not pairwise co-prime"
    result += a*s*m

  # Make sure we return the canonical solution.
  return result % N
result_final=chinese_remainder_theorem([(7,8),(0,7),(3,109),(46552,551753)])
print("a =",result_final)

a = 12736871
